name: Test
run-name: Testing new push from ${{ github.actor }}
on:
  push:
    branches: [feature/homepage]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  test:
    runs-on: self-hosted
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: Run Test Suites
        run: npm run test